name: Release

on:
  workflow_dispatch: {}

jobs:
  test:
    name: Test code
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml

  release:
    name: Release new version

    runs-on: ubuntu-latest
    container: node:22-bookworm-slim

    needs: test
    environment: release

    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Install git :)
        run: apt update && apt install -y git

      - name: Upgrade npm
        run: npm install --global npm@latest

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_SSH_KEY }}

      - name: Change directory ownership to the node user
        run: chown -R node:node .

      - name: Mark the working directory as safe
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Install dependencies
        run: su node -c 'npm ci && git config --unset core.hooksPath'

      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            conventional-changelog-conventionalcommits@^9.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
